services:
  bus_postgres:
   container_name: buspostgres
   image: postgres:14
   environment:
    POSTGRES_USER: bushexa
    POSTGRES_PASSWORD: WhenMyBusRun
    POSTGRES_DB: buslog
   ports:
    - "15432:5432"
   volumes:
    - ./postgres-data:/var/lib/postgresql/data
  bus:
   container_name: bus
   build:
    context: .
    dockerfile: Dockerfile
   ports:
    - "8017:8501"
   volumes:
    - ./logs:/app/logs
    - ./crawl:/app/crawl
    - ./infopages:/app/infopages
    - ./src:/app/src
    - ./app.py:/app/app.py
    - ./media:/app/media

networks:
  default:
    name: bushexa